### PR TITLE
Make it compatible with SSR

### PR DESCRIPTION
**Pull request by nathanloisel**
I remove the webpack configuration, because it must be handle by the main project.
I updated the README.md to explain how to configure webpack.

Any comment is welcome.

### CODE REVIEW

**Comment by viktorbergehall** [comment]
Thanks for the PR! 
Some thoughts:
- Why must Webpack be handled by the main project? Not debating, just curios.
- If I am to remove Webpack, wouldn't it be easier just to inline the styles in lcHOC.js? Rather than forcing the user to have a loader. I think it's key for the user to just install, import and use.

**Comment by nathanloisel** [comment]
> Why must Webpack be handled by the main project?

Because assets loading is handled differently depending on project configuration. For exemple with SSR, we handle style loading differently on the server than on the client side.

> If I am to remove Webpack, wouldn't it be easier just to inline the styles in lcHOC.js?

They can import the CSS using the HTML <link> element `<link rel="stylesheet" href="node_modules/lc-hoc/assets/lc-hoc.css" />`

I hope I answer well to your questions.

**Comment by viktorbergehall** [comment]
> They can import the CSS using the HTML element <link rel="stylesheet" href="node_modules/lc-hoc/assets/lc-hoc.css" />

I think that's a bit cumbersome. I suggest an approach where we skip lcHOC.css altogether and just use inline styles in React. Like
```es6
const styles = {
  position: 'relative'
  ...
  ...
}

...

render() {
      return(
        <div
          style={styles}
          ref={(ref) => this.lchoc = ref}>
            {super.render()}
        </div>
      );
    }
```

I can extend your PR later.

**Comment by viktorbergehall** [comment]
I've rewritten the hoc and removed the webpack dependency and more. I'm going to close this for now.

**Pull request closed without merging**
